-- IT Department Students (30 students, batch 2021)
INSERT INTO students (id, register_number, student_name, department, batch_year, email) VALUES
(gen_random_uuid(), '21IT001', 'Aarav Mehta', 'IT', 2021, 'aarav.mehta.it@university.edu'),
(gen_random_uuid(), '21IT002', 'Bhavya Nair', 'IT', 2021, 'bhavya.nair.it@university.edu'),
(gen_random_uuid(), '21IT003', 'Chetan Reddy', 'IT', 2021, 'chetan.reddy.it@university.edu'),
(gen_random_uuid(), '21IT004', 'Deepika Sharma', 'IT', 2021, 'deepika.sharma.it@university.edu'),
(gen_random_uuid(), '21IT005', 'Eshan Gupta', 'IT', 2021, 'eshan.gupta.it@university.edu'),
(gen_random_uuid(), '21IT006', 'Falguni Iyer', 'IT', 2021, 'falguni.iyer.it@university.edu'),
(gen_random_uuid(), '21IT007', 'Gaurav Joshi', 'IT', 2021, 'gaurav.joshi.it@university.edu'),
(gen_random_uuid(), '21IT008', 'Harini Krishnan', 'IT', 2021, 'harini.krishnan.it@university.edu'),
(gen_random_uuid(), '21IT009', 'Ishaan Patel', 'IT', 2021, 'ishaan.patel.it@university.edu'),
(gen_random_uuid(), '21IT010', 'Jaya Menon', 'IT', 2021, 'jaya.menon.it@university.edu'),
(gen_random_uuid(), '21IT011', 'Karan Desai', 'IT', 2021, 'karan.desai.it@university.edu'),
(gen_random_uuid(), '21IT012', 'Lavanya Rao', 'IT', 2021, 'lavanya.rao.it@university.edu'),
(gen_random_uuid(), '21IT013', 'Manish Kumar', 'IT', 2021, 'manish.kumar.it@university.edu'),
(gen_random_uuid(), '21IT014', 'Nandita Mukherjee', 'IT', 2021, 'nandita.mukherjee.it@university.edu'),
(gen_random_uuid(), '21IT015', 'Om Malhotra', 'IT', 2021, 'om.malhotra.it@university.edu'),
(gen_random_uuid(), '21IT016', 'Pallavi Singh', 'IT', 2021, 'pallavi.singh.it@university.edu'),
(gen_random_uuid(), '21IT017', 'Qasim Ali', 'IT', 2021, 'qasim.ali.it@university.edu'),
(gen_random_uuid(), '21IT018', 'Riya Verma', 'IT', 2021, 'riya.verma.it@university.edu'),
(gen_random_uuid(), '21IT019', 'Siddharth Bose', 'IT', 2021, 'siddharth.bose.it@university.edu'),
(gen_random_uuid(), '21IT020', 'Tanvi Pillai', 'IT', 2021, 'tanvi.pillai.it@university.edu'),
(gen_random_uuid(), '21IT021', 'Uday Tiwari', 'IT', 2021, 'uday.tiwari.it@university.edu'),
(gen_random_uuid(), '21IT022', 'Vaishnavi Ghosh', 'IT', 2021, 'vaishnavi.ghosh.it@university.edu'),
(gen_random_uuid(), '21IT023', 'Waqar Ahmed', 'IT', 2021, 'waqar.ahmed.it@university.edu'),
(gen_random_uuid(), '21IT024', 'Xerxes Pinto', 'IT', 2021, 'xerxes.pinto.it@university.edu'),
(gen_random_uuid(), '21IT025', 'Yamini Chatterjee', 'IT', 2021, 'yamini.chatterjee.it@university.edu'),
(gen_random_uuid(), '21IT026', 'Zara Khan', 'IT', 2021, 'zara.khan.it@university.edu'),
(gen_random_uuid(), '21IT027', 'Arpit Saxena', 'IT', 2021, 'arpit.saxena.it@university.edu'),
(gen_random_uuid(), '21IT028', 'Bindu Nambiar', 'IT', 2021, 'bindu.nambiar.it@university.edu'),
(gen_random_uuid(), '21IT029', 'Chirag Shah', 'IT', 2021, 'chirag.shah.it@university.edu'),
(gen_random_uuid(), '21IT030', 'Disha Pandey', 'IT', 2021, 'disha.pandey.it@university.edu')
ON CONFLICT (register_number) DO NOTHING;
