-- ECE Department Students (30 students, batch 2021)
INSERT INTO students (id, register_number, student_name, department, batch_year, email) VALUES
(gen_random_uuid(), '21EC001', 'Anand Pillai', 'ECE', 2021, 'anand.pillai.ece@university.edu'),
(gen_random_uuid(), '21EC002', 'Brindha Krishnan', 'ECE', 2021, 'brindha.krishnan.ece@university.edu'),
(gen_random_uuid(), '21EC003', 'Chakravarthy Rao', 'ECE', 2021, 'chakravarthy.rao.ece@university.edu'),
(gen_random_uuid(), '21EC004', 'Dhanya Nair', 'ECE', 2021, 'dhanya.nair.ece@university.edu'),
(gen_random_uuid(), '21EC005', 'Elango Sharma', 'ECE', 2021, 'elango.sharma.ece@university.edu'),
(gen_random_uuid(), '21EC006', 'Fathima Siddiqui', 'ECE', 2021, 'fathima.siddiqui.ece@university.edu'),
(gen_random_uuid(), '21EC007', 'Geetha Menon', 'ECE', 2021, 'geetha.menon.ece@university.edu'),
(gen_random_uuid(), '21EC008', 'Hariharan Iyer', 'ECE', 2021, 'hariharan.iyer.ece@university.edu'),
(gen_random_uuid(), '21EC009', 'Indumathi Patel', 'ECE', 2021, 'indumathi.patel.ece@university.edu'),
(gen_random_uuid(), '21EC010', 'Jaganmohana Rao', 'ECE', 2021, 'jaganmohana.rao.ece@university.edu'),
(gen_random_uuid(), '21EC011', 'Kamakshi Gupta', 'ECE', 2021, 'kamakshi.gupta.ece@university.edu'),
(gen_random_uuid(), '21EC012', 'Logesh Subramaniam', 'ECE', 2021, 'logesh.subramaniam.ece@university.edu'),
(gen_random_uuid(), '21EC013', 'Maheswari Desai', 'ECE', 2021, 'maheswari.desai.ece@university.edu'),
(gen_random_uuid(), '21EC014', 'Nagarajan Verma', 'ECE', 2021, 'nagarajan.verma.ece@university.edu'),
(gen_random_uuid(), '21EC015', 'Oviyaa Malhotra', 'ECE', 2021, 'oviyaa.malhotra.ece@university.edu'),
(gen_random_uuid(), '21EC016', 'Prasanna Kumar', 'ECE', 2021, 'prasanna.kumar.ece@university.edu'),
(gen_random_uuid(), '21EC017', 'Qais Ansari', 'ECE', 2021, 'qais.ansari.ece@university.edu'),
(gen_random_uuid(), '21EC018', 'Rani Chatterjee', 'ECE', 2021, 'rani.chatterjee.ece@university.edu'),
(gen_random_uuid(), '21EC019', 'Selvakumar Hegde', 'ECE', 2021, 'selvakumar.hegde.ece@university.edu'),
(gen_random_uuid(), '21EC020', 'Thenmozhii Narayanan', 'ECE', 2021, 'thenmozhii.narayanan.ece@university.edu'),
(gen_random_uuid(), '21EC021', 'Udhayakumar Singh', 'ECE', 2021, 'udhayakumar.singh.ece@university.edu'),
(gen_random_uuid(), '21EC022', 'Visalakshi Ghosh', 'ECE', 2021, 'visalakshi.ghosh.ece@university.edu'),
(gen_random_uuid(), '21EC023', 'Wajid Khan', 'ECE', 2021, 'wajid.khan.ece@university.edu'),
(gen_random_uuid(), '21EC024', 'Xiomara Pinto', 'ECE', 2021, 'xiomara.pinto.ece@university.edu'),
(gen_random_uuid(), '21EC025', 'Yasodha Bose', 'ECE', 2021, 'yasodha.bose.ece@university.edu'),
(gen_random_uuid(), '21EC026', 'Zuber Ahmed', 'ECE', 2021, 'zuber.ahmed.ece@university.edu'),
(gen_random_uuid(), '21EC027', 'Aravindhan Tiwari', 'ECE', 2021, 'aravindhan.tiwari.ece@university.edu'),
(gen_random_uuid(), '21EC028', 'Bhargavi Saxena', 'ECE', 2021, 'bhargavi.saxena.ece@university.edu'),
(gen_random_uuid(), '21EC029', 'Chinnadurai Joshi', 'ECE', 2021, 'chinnadurai.joshi.ece@university.edu'),
(gen_random_uuid(), '21EC030', 'Durgadevi Pandey', 'ECE', 2021, 'durgadevi.pandey.ece@university.edu')
ON CONFLICT (register_number) DO NOTHING;
