-- BME Department Students (30 students, batch 2021)
INSERT INTO students (id, register_number, student_name, department, batch_year, email) VALUES
(gen_random_uuid(), '21BM001', 'Akshara Pillai', 'BME', 2021, 'akshara.pillai.bme@university.edu'),
(gen_random_uuid(), '21BM002', 'Balaji Subramaniam', 'BME', 2021, 'balaji.subramaniam.bme@university.edu'),
(gen_random_uuid(), '21BM003', 'Chandana Rao', 'BME', 2021, 'chandana.rao.bme@university.edu'),
(gen_random_uuid(), '21BM004', 'Dhruv Malhotra', 'BME', 2021, 'dhruv.malhotra.bme@university.edu'),
(gen_random_uuid(), '21BM005', 'Esha Kapoor', 'BME', 2021, 'esha.kapoor.bme@university.edu'),
(gen_random_uuid(), '21BM006', 'Farhan Sheikh', 'BME', 2021, 'farhan.sheikh.bme@university.edu'),
(gen_random_uuid(), '21BM007', 'Gayatri Menon', 'BME', 2021, 'gayatri.menon.bme@university.edu'),
(gen_random_uuid(), '21BM008', 'Hari Prasad', 'BME', 2021, 'hari.prasad.bme@university.edu'),
(gen_random_uuid(), '21BM009', 'Indrani Dey', 'BME', 2021, 'indrani.dey.bme@university.edu'),
(gen_random_uuid(), '21BM010', 'Jagdish Verma', 'BME', 2021, 'jagdish.verma.bme@university.edu'),
(gen_random_uuid(), '21BM011', 'Kavitha Nair', 'BME', 2021, 'kavitha.nair.bme@university.edu'),
(gen_random_uuid(), '21BM012', 'Lokesh Iyer', 'BME', 2021, 'lokesh.iyer.bme@university.edu'),
(gen_random_uuid(), '21BM013', 'Meghna Sharma', 'BME', 2021, 'meghna.sharma.bme@university.edu'),
(gen_random_uuid(), '21BM014', 'Nikhil Sinha', 'BME', 2021, 'nikhil.sinha.bme@university.edu'),
(gen_random_uuid(), '21BM015', 'Oviya Krishnan', 'BME', 2021, 'oviya.krishnan.bme@university.edu'),
(gen_random_uuid(), '21BM016', 'Pranav Gupta', 'BME', 2021, 'pranav.gupta.bme@university.edu'),
(gen_random_uuid(), '21BM017', 'Qureshi Imran', 'BME', 2021, 'qureshi.imran.bme@university.edu'),
(gen_random_uuid(), '21BM018', 'Radha Mukherjee', 'BME', 2021, 'radha.mukherjee.bme@university.edu'),
(gen_random_uuid(), '21BM019', 'Suresh Bhat', 'BME', 2021, 'suresh.bhat.bme@university.edu'),
(gen_random_uuid(), '21BM020', 'Tara Patel', 'BME', 2021, 'tara.patel.bme@university.edu'),
(gen_random_uuid(), '21BM021', 'Umesh Reddy', 'BME', 2021, 'umesh.reddy.bme@university.edu'),
(gen_random_uuid(), '21BM022', 'Vidya Narayanan', 'BME', 2021, 'vidya.narayanan.bme@university.edu'),
(gen_random_uuid(), '21BM023', 'Wasim Khan', 'BME', 2021, 'wasim.khan.bme@university.edu'),
(gen_random_uuid(), '21BM024', 'Xena D''souza', 'BME', 2021, 'xena.dsouza.bme@university.edu'),
(gen_random_uuid(), '21BM025', 'Yasmin Ali', 'BME', 2021, 'yasmin.ali.bme@university.edu'),
(gen_random_uuid(), '21BM026', 'Zubair Ahmed', 'BME', 2021, 'zubair.ahmed.bme@university.edu'),
(gen_random_uuid(), '21BM027', 'Anil Chandra', 'BME', 2021, 'anil.chandra.bme@university.edu'),
(gen_random_uuid(), '21BM028', 'Bindiya Saxena', 'BME', 2021, 'bindiya.saxena.bme@university.edu'),
(gen_random_uuid(), '21BM029', 'Cyrus Patel', 'BME', 2021, 'cyrus.patel.bme@university.edu'),
(gen_random_uuid(), '21BM030', 'Devika Hegde', 'BME', 2021, 'devika.hegde.bme@university.edu')
ON CONFLICT (register_number) DO NOTHING;
