-- AIDS Department Students (30 students, batch 2021)
INSERT INTO students (id, register_number, student_name, department, batch_year, email) VALUES
(gen_random_uuid(), '21AD001', 'Aditi Joshi', 'AIDS', 2021, 'aditi.joshi.aids@university.edu'),
(gen_random_uuid(), '21AD002', 'Bhuvan Reddy', 'AIDS', 2021, 'bhuvan.reddy.aids@university.edu'),
(gen_random_uuid(), '21AD003', 'Charvi Sharma', 'AIDS', 2021, 'charvi.sharma.aids@university.edu'),
(gen_random_uuid(), '21AD004', 'Darshan Nair', 'AIDS', 2021, 'darshan.nair.aids@university.edu'),
(gen_random_uuid(), '21AD005', 'Ekta Gupta', 'AIDS', 2021, 'ekta.gupta.aids@university.edu'),
(gen_random_uuid(), '21AD006', 'Farida Begum', 'AIDS', 2021, 'farida.begum.aids@university.edu'),
(gen_random_uuid(), '21AD007', 'Girish Menon', 'AIDS', 2021, 'girish.menon.aids@university.edu'),
(gen_random_uuid(), '21AD008', 'Hina Patel', 'AIDS', 2021, 'hina.patel.aids@university.edu'),
(gen_random_uuid(), '21AD009', 'Ishan Verma', 'AIDS', 2021, 'ishan.verma.aids@university.edu'),
(gen_random_uuid(), '21AD010', 'Janaki Krishnan', 'AIDS', 2021, 'janaki.krishnan.aids@university.edu'),
(gen_random_uuid(), '21AD011', 'Kiran Malhotra', 'AIDS', 2021, 'kiran.malhotra.aids@university.edu'),
(gen_random_uuid(), '21AD012', 'Lipika Bose', 'AIDS', 2021, 'lipika.bose.aids@university.edu'),
(gen_random_uuid(), '21AD013', 'Mihir Rao', 'AIDS', 2021, 'mihir.rao.aids@university.edu'),
(gen_random_uuid(), '21AD014', 'Nisha Singh', 'AIDS', 2021, 'nisha.singh.aids@university.edu'),
(gen_random_uuid(), '21AD015', 'Omkar Desai', 'AIDS', 2021, 'omkar.desai.aids@university.edu'),
(gen_random_uuid(), '21AD016', 'Preethi Subramaniam', 'AIDS', 2021, 'preethi.subramaniam.aids@university.edu'),
(gen_random_uuid(), '21AD017', 'Qian Pinto', 'AIDS', 2021, 'qian.pinto.aids@university.edu'),
(gen_random_uuid(), '21AD018', 'Rashid Khan', 'AIDS', 2021, 'rashid.khan.aids@university.edu'),
(gen_random_uuid(), '21AD019', 'Srividya Pillai', 'AIDS', 2021, 'srividya.pillai.aids@university.edu'),
(gen_random_uuid(), '21AD020', 'Tejas Iyer', 'AIDS', 2021, 'tejas.iyer.aids@university.edu'),
(gen_random_uuid(), '21AD021', 'Urmila Mukherjee', 'AIDS', 2021, 'urmila.mukherjee.aids@university.edu'),
(gen_random_uuid(), '21AD022', 'Vikrant Ghosh', 'AIDS', 2021, 'vikrant.ghosh.aids@university.edu'),
(gen_random_uuid(), '21AD023', 'Winita Chatterjee', 'AIDS', 2021, 'winita.chatterjee.aids@university.edu'),
(gen_random_uuid(), '21AD024', 'Xavier Gomes', 'AIDS', 2021, 'xavier.gomes.aids@university.edu'),
(gen_random_uuid(), '21AD025', 'Yashoda Hegde', 'AIDS', 2021, 'yashoda.hegde.aids@university.edu'),
(gen_random_uuid(), '21AD026', 'Zahira Ansari', 'AIDS', 2021, 'zahira.ansari.aids@university.edu'),
(gen_random_uuid(), '21AD027', 'Aakash Tiwari', 'AIDS', 2021, 'aakash.tiwari.aids@university.edu'),
(gen_random_uuid(), '21AD028', 'Bhoomika Pandey', 'AIDS', 2021, 'bhoomika.pandey.aids@university.edu'),
(gen_random_uuid(), '21AD029', 'Chinmay Saxena', 'AIDS', 2021, 'chinmay.saxena.aids@university.edu'),
(gen_random_uuid(), '21AD030', 'Danika Narayanan', 'AIDS', 2021, 'danika.narayanan.aids@university.edu')
ON CONFLICT (register_number) DO NOTHING;
