-- AIML Department Students (30 students, batch 2021)
INSERT INTO students (id, register_number, student_name, department, batch_year, email) VALUES
(gen_random_uuid(), '21AM001', 'Abhinav Sharma', 'AIML', 2021, 'abhinav.sharma.aiml@university.edu'),
(gen_random_uuid(), '21AM002', 'Babita Nair', 'AIML', 2021, 'babita.nair.aiml@university.edu'),
(gen_random_uuid(), '21AM003', 'Chiranjeevi Reddy', 'AIML', 2021, 'chiranjeevi.reddy.aiml@university.edu'),
(gen_random_uuid(), '21AM004', 'Diya Menon', 'AIML', 2021, 'diya.menon.aiml@university.edu'),
(gen_random_uuid(), '21AM005', 'Eshwar Patel', 'AIML', 2021, 'eshwar.patel.aiml@university.edu'),
(gen_random_uuid(), '21AM006', 'Fareeha Khan', 'AIML', 2021, 'fareeha.khan.aiml@university.edu'),
(gen_random_uuid(), '21AM007', 'Govind Rao', 'AIML', 2021, 'govind.rao.aiml@university.edu'),
(gen_random_uuid(), '21AM008', 'Hemali Desai', 'AIML', 2021, 'hemali.desai.aiml@university.edu'),
(gen_random_uuid(), '21AM009', 'Imtiaz Siddiqui', 'AIML', 2021, 'imtiaz.siddiqui.aiml@university.edu'),
(gen_random_uuid(), '21AM010', 'Jyotsna Iyer', 'AIML', 2021, 'jyotsna.iyer.aiml@university.edu'),
(gen_random_uuid(), '21AM011', 'Kartik Malhotra', 'AIML', 2021, 'kartik.malhotra.aiml@university.edu'),
(gen_random_uuid(), '21AM012', 'Latha Krishnan', 'AIML', 2021, 'latha.krishnan.aiml@university.edu'),
(gen_random_uuid(), '21AM013', 'Mohit Verma', 'AIML', 2021, 'mohit.verma.aiml@university.edu'),
(gen_random_uuid(), '21AM014', 'Neelima Pillai', 'AIML', 2021, 'neelima.pillai.aiml@university.edu'),
(gen_random_uuid(), '21AM015', 'Omveer Singh', 'AIML', 2021, 'omveer.singh.aiml@university.edu'),
(gen_random_uuid(), '21AM016', 'Priya Mukherjee', 'AIML', 2021, 'priya.mukherjee.aiml@university.edu'),
(gen_random_uuid(), '21AM017', 'Qurratulain Bose', 'AIML', 2021, 'qurratulain.bose.aiml@university.edu'),
(gen_random_uuid(), '21AM018', 'Rupali Ghosh', 'AIML', 2021, 'rupali.ghosh.aiml@university.edu'),
(gen_random_uuid(), '21AM019', 'Surya Narayanan', 'AIML', 2021, 'surya.narayanan.aiml@university.edu'),
(gen_random_uuid(), '21AM020', 'Triveni Hegde', 'AIML', 2021, 'triveni.hegde.aiml@university.edu'),
(gen_random_uuid(), '21AM021', 'Ujjwal Tiwari', 'AIML', 2021, 'ujjwal.tiwari.aiml@university.edu'),
(gen_random_uuid(), '21AM022', 'Veda Saxena', 'AIML', 2021, 'veda.saxena.aiml@university.edu'),
(gen_random_uuid(), '21AM023', 'Waseem Ansari', 'AIML', 2021, 'waseem.ansari.aiml@university.edu'),
(gen_random_uuid(), '21AM024', 'Xyla Fernandez', 'AIML', 2021, 'xyla.fernandez.aiml@university.edu'),
(gen_random_uuid(), '21AM025', 'Yogesh Pandey', 'AIML', 2021, 'yogesh.pandey.aiml@university.edu'),
(gen_random_uuid(), '21AM026', 'Zinia Chatterjee', 'AIML', 2021, 'zinia.chatterjee.aiml@university.edu'),
(gen_random_uuid(), '21AM027', 'Ajit Kumar', 'AIML', 2021, 'ajit.kumar.aiml@university.edu'),
(gen_random_uuid(), '21AM028', 'Bharat Joshi', 'AIML', 2021, 'bharat.joshi.aiml@university.edu'),
(gen_random_uuid(), '21AM029', 'Charu Gupta', 'AIML', 2021, 'charu.gupta.aiml@university.edu'),
(gen_random_uuid(), '21AM030', 'Devansh Sharma', 'AIML', 2021, 'devansh.sharma.aiml@university.edu')
ON CONFLICT (register_number) DO NOTHING;
