-- MDE Department Students (30 students, batch 2021)
INSERT INTO students (id, register_number, student_name, department, batch_year, email) VALUES
(gen_random_uuid(), '21MD001', 'Adarsh Pillai', 'MDE', 2021, 'adarsh.pillai.mde@university.edu'),
(gen_random_uuid(), '21MD002', 'Bhavani Reddy', 'MDE', 2021, 'bhavani.reddy.mde@university.edu'),
(gen_random_uuid(), '21MD003', 'Chethan Nair', 'MDE', 2021, 'chethan.nair.mde@university.edu'),
(gen_random_uuid(), '21MD004', 'Divya Menon', 'MDE', 2021, 'divya.menon.mde@university.edu'),
(gen_random_uuid(), '21MD005', 'Eshaan Gupta', 'MDE', 2021, 'eshaan.gupta.mde@university.edu'),
(gen_random_uuid(), '21MD006', 'Faizal Sheikh', 'MDE', 2021, 'faizal.sheikh.mde@university.edu'),
(gen_random_uuid(), '21MD007', 'Gopika Krishnan', 'MDE', 2021, 'gopika.krishnan.mde@university.edu'),
(gen_random_uuid(), '21MD008', 'Harshit Verma', 'MDE', 2021, 'harshit.verma.mde@university.edu'),
(gen_random_uuid(), '21MD009', 'Isha Malhotra', 'MDE', 2021, 'isha.malhotra.mde@university.edu'),
(gen_random_uuid(), '21MD010', 'Jayant Rao', 'MDE', 2021, 'jayant.rao.mde@university.edu'),
(gen_random_uuid(), '21MD011', 'Kalyani Iyer', 'MDE', 2021, 'kalyani.iyer.mde@university.edu'),
(gen_random_uuid(), '21MD012', 'Lohith Desai', 'MDE', 2021, 'lohith.desai.mde@university.edu'),
(gen_random_uuid(), '21MD013', 'Madhu Sharma', 'MDE', 2021, 'madhu.sharma.mde@university.edu'),
(gen_random_uuid(), '21MD014', 'Naveen Patel', 'MDE', 2021, 'naveen.patel.mde@university.edu'),
(gen_random_uuid(), '21MD015', 'Ojas Bose', 'MDE', 2021, 'ojas.bose.mde@university.edu'),
(gen_random_uuid(), '21MD016', 'Pavithra Narayanan', 'MDE', 2021, 'pavithra.narayanan.mde@university.edu'),
(gen_random_uuid(), '21MD017', 'Qadir Ansari', 'MDE', 2021, 'qadir.ansari.mde@university.edu'),
(gen_random_uuid(), '21MD018', 'Rekha Mukherjee', 'MDE', 2021, 'rekha.mukherjee.mde@university.edu'),
(gen_random_uuid(), '21MD019', 'Sachin Tiwari', 'MDE', 2021, 'sachin.tiwari.mde@university.edu'),
(gen_random_uuid(), '21MD020', 'Trupti Ghosh', 'MDE', 2021, 'trupti.ghosh.mde@university.edu'),
(gen_random_uuid(), '21MD021', 'Usha Hegde', 'MDE', 2021, 'usha.hegde.mde@university.edu'),
(gen_random_uuid(), '21MD022', 'Vinod Saxena', 'MDE', 2021, 'vinod.saxena.mde@university.edu'),
(gen_random_uuid(), '21MD023', 'Wahida Begum', 'MDE', 2021, 'wahida.begum.mde@university.edu'),
(gen_random_uuid(), '21MD024', 'Xander Fernandez', 'MDE', 2021, 'xander.fernandez.mde@university.edu'),
(gen_random_uuid(), '21MD025', 'Yuvraj Singh', 'MDE', 2021, 'yuvraj.singh.mde@university.edu'),
(gen_random_uuid(), '21MD026', 'Zeenat Khatoon', 'MDE', 2021, 'zeenat.khatoon.mde@university.edu'),
(gen_random_uuid(), '21MD027', 'Akash Chatterjee', 'MDE', 2021, 'akash.chatterjee.mde@university.edu'),
(gen_random_uuid(), '21MD028', 'Brinda Pillai', 'MDE', 2021, 'brinda.pillai.mde@university.edu'),
(gen_random_uuid(), '21MD029', 'Chandrakant Kumar', 'MDE', 2021, 'chandrakant.kumar.mde@university.edu'),
(gen_random_uuid(), '21MD030', 'Dhanashri Joshi', 'MDE', 2021, 'dhanashri.joshi.mde@university.edu')
ON CONFLICT (register_number) DO NOTHING;
