-- MECH Department Students (30 students, batch 2021)
INSERT INTO students (id, register_number, student_name, department, batch_year, email) VALUES
(gen_random_uuid(), '21ME001', 'Aravind Pillai', 'MECH', 2021, 'aravind.pillai.mech@university.edu'),
(gen_random_uuid(), '21ME002', 'Boopathi Reddy', 'MECH', 2021, 'boopathi.reddy.mech@university.edu'),
(gen_random_uuid(), '21ME003', 'Chidambaram Nair', 'MECH', 2021, 'chidambaram.nair.mech@university.edu'),
(gen_random_uuid(), '21ME004', 'Dhanasekar Sharma', 'MECH', 2021, 'dhanasekar.sharma.mech@university.edu'),
(gen_random_uuid(), '21ME005', 'Elumalai Gupta', 'MECH', 2021, 'elumalai.gupta.mech@university.edu'),
(gen_random_uuid(), '21ME006', 'Fathima Nisha', 'MECH', 2021, 'fathima.nisha.mech@university.edu'),
(gen_random_uuid(), '21ME007', 'Gopalakrishnan Menon', 'MECH', 2021, 'gopalakrishnan.menon.mech@university.edu'),
(gen_random_uuid(), '21ME008', 'Hariharasudhan Iyer', 'MECH', 2021, 'hariharasudhan.iyer.mech@university.edu'),
(gen_random_uuid(), '21ME009', 'Ilayaraja Patel', 'MECH', 2021, 'ilayaraja.patel.mech@university.edu'),
(gen_random_uuid(), '21ME010', 'Janakiram Rao', 'MECH', 2021, 'janakiram.rao.mech@university.edu'),
(gen_random_uuid(), '21ME011', 'Kalaivani Krishnan', 'MECH', 2021, 'kalaivani.krishnan.mech@university.edu'),
(gen_random_uuid(), '21ME012', 'Loganathan Desai', 'MECH', 2021, 'loganathan.desai.mech@university.edu'),
(gen_random_uuid(), '21ME013', 'Meenakshi Verma', 'MECH', 2021, 'meenakshi.verma.mech@university.edu'),
(gen_random_uuid(), '21ME014', 'Narendran Malhotra', 'MECH', 2021, 'narendran.malhotra.mech@university.edu'),
(gen_random_uuid(), '21ME015', 'Oviya Narayanan', 'MECH', 2021, 'oviya.narayanan.mech@university.edu'),
(gen_random_uuid(), '21ME016', 'Palanivel Singh', 'MECH', 2021, 'palanivel.singh.mech@university.edu'),
(gen_random_uuid(), '21ME017', 'Qabeel Hussain', 'MECH', 2021, 'qabeel.hussain.mech@university.edu'),
(gen_random_uuid(), '21ME018', 'Ramachandran Hegde', 'MECH', 2021, 'ramachandran.hegde.mech@university.edu'),
(gen_random_uuid(), '21ME019', 'Shanmugam Ghosh', 'MECH', 2021, 'shanmugam.ghosh.mech@university.edu'),
(gen_random_uuid(), '21ME020', 'Thiruvenkatam Bose', 'MECH', 2021, 'thiruvenkatam.bose.mech@university.edu'),
(gen_random_uuid(), '21ME021', 'Ulaganathan Tiwari', 'MECH', 2021, 'ulaganathan.tiwari.mech@university.edu'),
(gen_random_uuid(), '21ME022', 'Veerasamy Saxena', 'MECH', 2021, 'veerasamy.saxena.mech@university.edu'),
(gen_random_uuid(), '21ME023', 'Waqas Sheikh', 'MECH', 2021, 'waqas.sheikh.mech@university.edu'),
(gen_random_uuid(), '21ME024', 'Xylan Rodrigues', 'MECH', 2021, 'xylan.rodrigues.mech@university.edu'),
(gen_random_uuid(), '21ME025', 'Yogaraj Chatterjee', 'MECH', 2021, 'yogaraj.chatterjee.mech@university.edu'),
(gen_random_uuid(), '21ME026', 'Zabiullah Khan', 'MECH', 2021, 'zabiullah.khan.mech@university.edu'),
(gen_random_uuid(), '21ME027', 'Annamalai Pandey', 'MECH', 2021, 'annamalai.pandey.mech@university.edu'),
(gen_random_uuid(), '21ME028', 'Balasubramaniam Joshi', 'MECH', 2021, 'balasubramaniam.joshi.mech@university.edu'),
(gen_random_uuid(), '21ME029', 'Chinnaswamy Kumar', 'MECH', 2021, 'chinnaswamy.kumar.mech@university.edu'),
(gen_random_uuid(), '21ME030', 'Dhandapani Pillai', 'MECH', 2021, 'dhandapani.pillai.mech@university.edu')
ON CONFLICT (register_number) DO NOTHING;
