-- CIVIL Department Students (30 students, batch 2021)
INSERT INTO students (id, register_number, student_name, department, batch_year, email) VALUES
(gen_random_uuid(), '21CV001', 'Anbarasan Pillai', 'CIVIL', 2021, 'anbarasan.pillai.civil@university.edu'),
(gen_random_uuid(), '21CV002', 'Bhuvaneshwari Nair', 'CIVIL', 2021, 'bhuvaneshwari.nair.civil@university.edu'),
(gen_random_uuid(), '21CV003', 'Chandrasekaran Reddy', 'CIVIL', 2021, 'chandrasekaran.reddy.civil@university.edu'),
(gen_random_uuid(), '21CV004', 'Dhanalakshmi Sharma', 'CIVIL', 2021, 'dhanalakshmi.sharma.civil@university.edu'),
(gen_random_uuid(), '21CV005', 'Elangovan Gupta', 'CIVIL', 2021, 'elangovan.gupta.civil@university.edu'),
(gen_random_uuid(), '21CV006', 'Fareeda Begum', 'CIVIL', 2021, 'fareeda.begum.civil@university.edu'),
(gen_random_uuid(), '21CV007', 'Gajendra Menon', 'CIVIL', 2021, 'gajendra.menon.civil@university.edu'),
(gen_random_uuid(), '21CV008', 'Hemamalini Iyer', 'CIVIL', 2021, 'hemamalini.iyer.civil@university.edu'),
(gen_random_uuid(), '21CV009', 'Ilavarasan Krishnan', 'CIVIL', 2021, 'ilavarasan.krishnan.civil@university.edu'),
(gen_random_uuid(), '21CV010', 'Jaishree Rao', 'CIVIL', 2021, 'jaishree.rao.civil@university.edu'),
(gen_random_uuid(), '21CV011', 'Kanimozhi Desai', 'CIVIL', 2021, 'kanimozhi.desai.civil@university.edu'),
(gen_random_uuid(), '21CV012', 'Lakshminarayanan Patel', 'CIVIL', 2021, 'lakshminarayanan.patel.civil@university.edu'),
(gen_random_uuid(), '21CV013', 'Malarvizhi Verma', 'CIVIL', 2021, 'malarvizhi.verma.civil@university.edu'),
(gen_random_uuid(), '21CV014', 'Natarajan Malhotra', 'CIVIL', 2021, 'natarajan.malhotra.civil@university.edu'),
(gen_random_uuid(), '21CV015', 'Oothuvelankanni Singh', 'CIVIL', 2021, 'oothuvelankanni.singh.civil@university.edu'),
(gen_random_uuid(), '21CV016', 'Poonguzhali Narayanan', 'CIVIL', 2021, 'poonguzhali.narayanan.civil@university.edu'),
(gen_random_uuid(), '21CV017', 'Qaiyum Ansari', 'CIVIL', 2021, 'qaiyum.ansari.civil@university.edu'),
(gen_random_uuid(), '21CV018', 'Ranjithkumar Hegde', 'CIVIL', 2021, 'ranjithkumar.hegde.civil@university.edu'),
(gen_random_uuid(), '21CV019', 'Senthilkumar Ghosh', 'CIVIL', 2021, 'senthilkumar.ghosh.civil@university.edu'),
(gen_random_uuid(), '21CV020', 'Tamilarasi Bose', 'CIVIL', 2021, 'tamilarasi.bose.civil@university.edu'),
(gen_random_uuid(), '21CV021', 'Udayakumar Tiwari', 'CIVIL', 2021, 'udayakumar.tiwari.civil@university.edu'),
(gen_random_uuid(), '21CV022', 'Vijayakumar Saxena', 'CIVIL', 2021, 'vijayakumar.saxena.civil@university.edu'),
(gen_random_uuid(), '21CV023', 'Waseem Ullah', 'CIVIL', 2021, 'waseem.ullah.civil@university.edu'),
(gen_random_uuid(), '21CV024', 'Xenophon Rodrigues', 'CIVIL', 2021, 'xenophon.rodrigues.civil@university.edu'),
(gen_random_uuid(), '21CV025', 'Yogalakshmi Chatterjee', 'CIVIL', 2021, 'yogalakshmi.chatterjee.civil@university.edu'),
(gen_random_uuid(), '21CV026', 'Zulfiqar Ahmed', 'CIVIL', 2021, 'zulfiqar.ahmed.civil@university.edu'),
(gen_random_uuid(), '21CV027', 'Arthi Pandey', 'CIVIL', 2021, 'arthi.pandey.civil@university.edu'),
(gen_random_uuid(), '21CV028', 'Balamurugan Joshi', 'CIVIL', 2021, 'balamurugan.joshi.civil@university.edu'),
(gen_random_uuid(), '21CV029', 'Chellamuthu Kumar', 'CIVIL', 2021, 'chellamuthu.kumar.civil@university.edu'),
(gen_random_uuid(), '21CV030', 'Dharmaraj Pillai', 'CIVIL', 2021, 'dharmaraj.pillai.civil@university.edu')
ON CONFLICT (register_number) DO NOTHING;
