-- EEE Department Students (30 students, batch 2021)
INSERT INTO students (id, register_number, student_name, department, batch_year, email) VALUES
(gen_random_uuid(), '21EE001', 'Abishek Nair', 'EEE', 2021, 'abishek.nair.eee@university.edu'),
(gen_random_uuid(), '21EE002', 'Baskar Reddy', 'EEE', 2021, 'baskar.reddy.eee@university.edu'),
(gen_random_uuid(), '21EE003', 'Chandra Sharma', 'EEE', 2021, 'chandra.sharma.eee@university.edu'),
(gen_random_uuid(), '21EE004', 'Deepthi Gupta', 'EEE', 2021, 'deepthi.gupta.eee@university.edu'),
(gen_random_uuid(), '21EE005', 'Eswar Krishnan', 'EEE', 2021, 'eswar.krishnan.eee@university.edu'),
(gen_random_uuid(), '21EE006', 'Feba Thomas', 'EEE', 2021, 'feba.thomas.eee@university.edu'),
(gen_random_uuid(), '21EE007', 'Guhan Menon', 'EEE', 2021, 'guhan.menon.eee@university.edu'),
(gen_random_uuid(), '21EE008', 'Himaja Patel', 'EEE', 2021, 'himaja.patel.eee@university.edu'),
(gen_random_uuid(), '21EE009', 'Ilamaran Subramaniam', 'EEE', 2021, 'ilamaran.subramaniam.eee@university.edu'),
(gen_random_uuid(), '21EE010', 'Jeevan Rao', 'EEE', 2021, 'jeevan.rao.eee@university.edu'),
(gen_random_uuid(), '21EE011', 'Keerthana Iyer', 'EEE', 2021, 'keerthana.iyer.eee@university.edu'),
(gen_random_uuid(), '21EE012', 'Lokeshwari Desai', 'EEE', 2021, 'lokeshwari.desai.eee@university.edu'),
(gen_random_uuid(), '21EE013', 'Muthukumar Pillai', 'EEE', 2021, 'muthukumar.pillai.eee@university.edu'),
(gen_random_uuid(), '21EE014', 'Niranjana Singh', 'EEE', 2021, 'niranjana.singh.eee@university.edu'),
(gen_random_uuid(), '21EE015', 'Omsai Malhotra', 'EEE', 2021, 'omsai.malhotra.eee@university.edu'),
(gen_random_uuid(), '21EE016', 'Pavithra Kumar', 'EEE', 2021, 'pavithra.kumar.eee@university.edu'),
(gen_random_uuid(), '21EE017', 'Qadir Hussain', 'EEE', 2021, 'qadir.hussain.eee@university.edu'),
(gen_random_uuid(), '21EE018', 'Ramesh Narayanan', 'EEE', 2021, 'ramesh.narayanan.eee@university.edu'),
(gen_random_uuid(), '21EE019', 'Subashini Hegde', 'EEE', 2021, 'subashini.hegde.eee@university.edu'),
(gen_random_uuid(), '21EE020', 'Tamilselvi Bose', 'EEE', 2021, 'tamilselvi.bose.eee@university.edu'),
(gen_random_uuid(), '21EE021', 'Umanath Verma', 'EEE', 2021, 'umanath.verma.eee@university.edu'),
(gen_random_uuid(), '21EE022', 'Vijayalakshmi Ghosh', 'EEE', 2021, 'vijayalakshmi.ghosh.eee@university.edu'),
(gen_random_uuid(), '21EE023', 'Wasif Ali', 'EEE', 2021, 'wasif.ali.eee@university.edu'),
(gen_random_uuid(), '21EE024', 'Xavia Rodrigues', 'EEE', 2021, 'xavia.rodrigues.eee@university.edu'),
(gen_random_uuid(), '21EE025', 'Yazhini Chatterjee', 'EEE', 2021, 'yazhini.chatterjee.eee@university.edu'),
(gen_random_uuid(), '21EE026', 'Ziyad Ahmed', 'EEE', 2021, 'ziyad.ahmed.eee@university.edu'),
(gen_random_uuid(), '21EE027', 'Amarnath Tiwari', 'EEE', 2021, 'amarnath.tiwari.eee@university.edu'),
(gen_random_uuid(), '21EE028', 'Bhavadharini Saxena', 'EEE', 2021, 'bhavadharini.saxena.eee@university.edu'),
(gen_random_uuid(), '21EE029', 'Chandrasekhar Joshi', 'EEE', 2021, 'chandrasekhar.joshi.eee@university.edu'),
(gen_random_uuid(), '21EE030', 'Divyabharathi Pandey', 'EEE', 2021, 'divyabharathi.pandey.eee@university.edu')
ON CONFLICT (register_number) DO NOTHING;
